allow cycling through auto-complete
4d49/godot-console pull request #10
Opened 2024-05-09 05:52 UTC by stevenctl

I have a bunch of commands with common prefixes. It's easier for me to spam tab a few times. 

```
terrain_gui
terrain_reset
terrain_debug
terrain_shader <int>
```

In this PR:

* Add an "autocomplete index". This is reset to 0 when any item changes. 
* The item in the list selected by that index gets a `*` prefix in the tooltip display
* Enter will select autocomplete while the tooltip is visible
* Tab, left arrow and right arrow, will cycle through the autocomplete selections

At first I had only the arrows to cycle through, but it was cumbersome to do `ter<arrow><arrow><tab><enter>` versus repeated keys accessible from homerow like `ter<tab><tab><enter><enter>`

2024-05-09 05:53 UTC, stevenctl commented
Please let me know what cleanups you'd like to see for merging this. I'm definitely breaking the control scheme others would be used to.. maybe it's welcome but maybe I can add a setting for that.

2024-05-09 07:20 UTC, 4d49 requested changes

2024-05-09 07:20 UTC, 4d49 commented on scripts/console.gd
> +func autocomplete_command(string: String, selected_index: int=-1) -> String:
```suggestion
func autocomplete_command(string: String, selected_index: int= -1) -> String:
```

2024-05-09 07:20 UTC, 4d49 commented on scripts/console.gd
> +			if selected_index < 0 || i == selected_index:
```suggestion
			if selected_index < 0 or i == selected_index:
```

2024-05-09 07:20 UTC, 4d49 commented on scripts/console.gd
> +func autocomplete_list(string: String, selected_index: int=-1) -> PackedStringArray:
```suggestion
func autocomplete_list(string: String, selected_index: int= -1) -> PackedStringArray:
```

2024-05-09 07:20 UTC, 4d49 commented on scripts/console.gd
> +	var i = 0
```suggestion
	var i: int = 0
```

2024-05-09 11:17 UTC, 4d49 requested changes

2024-05-09 11:17 UTC, 4d49 commented on scripts/console_container.gd
> +func _show_autocomplete(text):
```suggestion
func _show_autocomplete(text: String) -> void:
```

2024-05-09 11:17 UTC, 4d49 commented on scripts/console_container.gd
> +	var autocomplete := _console.autocomplete_list(_console_input.text)
```suggestion
	var autocomplete: PackedStringArray = _console.autocomplete_list(_console_input.get_text())
```

2024-05-09 11:17 UTC, 4d49 commented on scripts/console_container.gd
> +	_autocomplete_index = (_autocomplete_index + direction) % len(autocomplete)
The `wrapi` method is more intuitive.
```suggestion
	_autocomplete_index = wrapi(_autocomplete_index + direction, 0, autocomplete.size())
```

2024-05-09 11:40 UTC, 4d49 requested changes

2024-05-09 11:40 UTC, 4d49 commented on scripts/console.gd
> +			i += 1
```suggestion
	var command_list: PackedStringArray = get_command_list()
	for i: int in command_list.size():
		if not command_list[i].begins_with(string):
			continue

		if i == selected_index:
			list.push_back("*\t" + command_list[i] + "[/b]")
		else:
			list.push_back("\t" + command_list[i])
```

2024-05-09 11:40 UTC, 4d49 commented on scripts/console_container.gd
>  		_tooltip_panel.show()
Move method before `_on_input_text_changed`.
```suggestion
```

2024-05-09 11:40 UTC, 4d49 commented on scripts/console_container.gd
```suggestion


func _show_autocomplete(text: String) -> void:
	var autocomplete := PackedStringArray() if text.is_empty() else _console.autocomplete_list(text, _autocomplete_index)

	if autocomplete.is_empty():
		_tooltip_panel.hide()
	else:
		_tooltip_label.set_text("\n".join(autocomplete))
		_tooltip_panel.show()


```

2024-05-09 11:40 UTC, 4d49 commented on scripts/console_container.gd
Maybe using `wrapi` would be more illustrative?
```suggestion


func _cycle_autocomplete(direction: int) -> void:
	var autocomplete: PackedStringArray = _console.autocomplete_list(_console_input.get_text())
	_autocomplete_index = wrapi(_autocomplete_index + direction, 0, autocomplete.size())
	_show_autocomplete(_console_input.get_text())

```

2024-05-09 11:42 UTC, 4d49 commented
You also have some empty lines and whitespaces. Press `CTRL + ALT + T` in the Godot code editor to get rid of them.

2024-05-09 15:38 UTC, stevenctl commented
> You also have some empty lines and whitespaces. Press CTRL + ALT + T in the Godot code editor to get rid of them.

Using an external editor, I'll try to get that fixed as well. Thanks for taking a look so quickly.

2024-05-10 04:58 UTC, 4d49 commented
If the actocomplete command is one, the `Tab` button does not complement the command. For example, the `help` command is not autocomplete.

2024-05-10 04:59 UTC, 4d49 commented
Also, please run the `git squash` command to glue your commits together.

2024-05-10 05:06 UTC, 4d49 requested changes

2024-05-10 05:06 UTC, 4d49 commented on scripts/console.gd
> +func autocomplete_command(string: String, selected_index: int=-1) -> String:
```suggestion
func autocomplete_command(string: String, selected_index: int= -1) -> String:
```

2024-05-10 05:06 UTC, 4d49 commented on scripts/console.gd
> +func autocomplete_command(string: String, selected_index: int= -1) -> String:
```suggestion
func autocomplete_command(string: String, selected_index: int = -1) -> String:
```

2024-05-10 05:06 UTC, 4d49 commented on scripts/console.gd
> +	var i = 0
```suggestion
	var i: int = 0
```

2024-05-10 05:06 UTC, 4d49 commented on scripts/console.gd
> +func autocomplete_list(string: String, selected_index: int= -1) -> PackedStringArray:
```suggestion
func autocomplete_list(string: String, selected_index: int = -1) -> PackedStringArray:
```

2024-05-10 05:06 UTC, 4d49 commented on scripts/console.gd
> +	var i = 0
```suggestion
	var i: int = 0
```

2024-05-10 05:06 UTC, 4d49 commented on scripts/console_container.gd
> +
```suggestion
```

2024-05-10 05:26 UTC, merged

2024-05-10 05:29 UTC, 4d49 commented
Thank you! I've been thinking about something like this for a long time, but never got around to it.